### ISSUE TITLE
Please allow to skip MELPA repo fetch even on first quelpa initialization

### ISSUE THREAD

**Issue by ackalker** [quelpa/quelpa#103]
I'm aware that setting `quelpa-update-melpa-p` to `nil` before requiring quelpa stops it updating the local copy of the MELPA repo, but quelpa will still clone the repository the very first time it is initialized.
It would be nice if I could prevent quelpa from cloning the repo in the first place, because I use only custom recipes (along with `quelpa-use-package`) to install packages directly from Github repositories.

This appears to be related to the logic in [these forms](https://github.com/quelpa/quelpa/blob/3aa591ab8f610ff13665860be99cb8819d08a72f/quelpa.el#L420-L421).

**Comment by vyp** [comment]
I can reproduce this with `emacs -q -l init.el` (emacs 24.5.2) where `init.el` is:

``` elisp
(package-initialize)
(unless (require 'quelpa nil t)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))
(quelpa '(dash :fetcher github :repo "magnars/dash.el" :files ("dash.el")))
```

Of course, you have to make sure `quelpa-build-dir/package-build` (usually `~/.emacs.d/quelpa/build/package-build`) does not exist, to see it clone melpa. (I chose dash because I did not already have it installed, and it seems like it has no other dependencies.)

However, I think there are slightly different usecases here. You do not use the melpa recipes at all. But consider the case of someone who does use the melpa recipes, but just wants to inhibit these updates to the local melpa repo to help with startup times. (Perhaps they update it manually.) For them, not cloning the melpa recipes in the first place if it doesn't even exist will not work, because then their forms like `(quelpa 'magit)` in their init file will not work, if I have understood correctly.

With that being said, I would actually like the ability to not have to clone the melpa repository at all too, because I also do not use any melpa recipes (as in, directly from the repo). So I think we may need/want a new option to set for this @steckerhalter? (Which when set, will not clone melpa at all, and will therefore require that the user provides their own custom recipes.)

If you'r wondering, the reason I haven't actually come across this issue even though I also do not use melpa recipes, is because quelpa depends on the package-build.el library, which actually lives in the melpa repository (with the recipes) itself. So my setup actually already requires to clone the melpa repository because I use git submodules, meaning that my `quelpa-build-dir/package-build/.git` is already created when I install package-build (meaning the melpa repository isn't cloned). So I may or may not have come across this issue when https://github.com/melpa/melpa/issues/3570 is completed, if you didn't report this. ;)

**Comment by steckerhalter** [comment]
@ackalker it shouldn't even clone the repo if you set `quelpa-update-melpa-p` to `nil` before quelpa's invocation.
@vyp you didn't set `quelpa-upate-melpa-p` to `nil` in your test case.

**Comment by vyp** [comment]
@steckerhalter Oh I believe I incorrectly copy pasted. I will try it again later just to make sure then.

**Comment by ackalker** [comment]
@steckerhalter ah okay, thanks!

**Comment by zakame** [comment]
I tried @vyp 's test case with `(setq quelpa-update-melpa-p nil)` before it, it fails (that is, it still checks out the melpa.git repo upon invoking `(quelpa ...)`.

The forms higlighted by @ackalker above are indeed meaningless in this case, since the inner `(and)` in

```
    (or (and (null quelpa-update-melpa-p)
             (file-exists-p (expand-file-name ".git" dir)))
         (condition-case err ;; check out melpa here...))
```
will fail anyway since the `~/.emacs.d/quelpa/build/package-build/.git` won't even be there in the first place.

The fix I found working for me is simply changing the form to this:

```
    (or (or (null quelpa-update-melpa-p)
             (file-exists-p (expand-file-name ".git" dir)))
         (condition-case err ;; check out melpa here...))
```

**Comment by steckerhalter** [comment]
@zakame I see what you mean. This isn't a good solution though because it makes `quelpa-update-melpa-p` to mean that the melpa repo isn't checked out at all (and not just not updated).

Maybe a new variable like `quelpa-checkout-melpa-p` would work? I will have to think about it a little bit. Any suggestions?

**Comment by zakame** [comment]
@steckerhalter `quelpa-checkout-melpa-p` sounds good.  I agree, `quelpa-update-melpa-p` should just refer to whether we update the melpa checkout, not necessarily to check if we _want_ to check out.  I'll update my PR to try this out :+1:

**Comment by vyp** [comment]
+1 to the new variable, I think @steckerhalter is right.

PS - Sorry for not getting back on this, I've actually been meaning to soon, but unfortunately real life for the past month has caught up to me. :(

**Comment by zakame** [comment]
Updated PR, it now has the new variable and tests it in `quelpa-setup-p` instead of changing logic in `quelpa-checkout-melpa`.

**Comment by steckerhalter** [comment]
I think that looks fine. Could you add some documentation to the readme?

**Comment by zakame** [comment]
Oops, forgot that.  Done :muscle:

**Comment by ackalker** [comment]
Thanks to all for looking into this :-)
