### ISSUE TITLE
how do I specify a branch?

### ISSUE THREAD

**Issue by ninrod** [quelpa/quelpa#116]
I was thinking of something in the lines of:

(quelpa multiple-cursors
           :repo "myrjlola/multiple-cursors.el"
           :branch "evil-compat"))

can it be done?

**Comment by vyp** [comment]
Yes that should be correct according to https://github.com/melpa/melpa#recipe-format.

By the way just remember in this example you are missing the `:fetcher`, and "myrjlola" should be "myrjola". Not to mention the non-matching parentheses (the recipe itself should be a list).

Closing because it seems like you have already figured it out from https://github.com/quelpa/quelpa-use-package/issues/8, but definitely don't hesitate to let us know if you still have issues. :)
