### ISSUE TITLE
What is the difference between C-u M-x quelpa and M-x quelpa-upgrade?

### ISSUE THREAD

**Issue by tsuu32** [quelpa/quelpa#163]
Recent commits completely changed `M-x quelpa-upgrade` behavior.
This is breaking change, but no problem for me because I have never used `M-x quelpa-upgrade`.

I use `C-u M-x quelpa` to upgrade installed packages.
What is the difference between `C-u M-x quelpa` and current `M-x quelpa-upgrade`?

**Comment by kiennq** [comment]
`C-u M-x quelpa` upgrade packages which are already on Melpa, whereas `M-x quelpa-upgrade` upgrade packages that are installed with Quelpa.
So in case you use Quelpa to install packages that are not on Melpa, the only way to upgrade those packages is using `quelpa-upgrade`.

**Comment by tsuu32** [comment]
> So in case you use Quelpa to install packages that are not on Melpa, the only way to upgrade those packages is using quelpa-upgrade.

I customize `quelpa-melpa-recipe-stores`. Specifically, I put `(add-to-list 'quelpa-melpa-recipe-stores "~/.emacs.d/quelpa-user/recipes")` in init file.
I have `~/.emacs.d/quelpa-user/recipes/spinner` file which the following code is written.
```
(spinner :fetcher github :repo "Malabarba/spinner.el")
```
So I can upgrade spinner package that are not on Melpa by `C-u M-x quelpa`.

Is this a incorrent way to use `quelpa-melpa-recipe-stores`?

**Comment by kiennq** [comment]
> Is this a incorrect way to use `quelpa-melpa-recipe-stores`?

No, it's just inconvenient. Normally I expected that all package installed via `quelpa` can be upgrade without having write the recipe again somewhere.
For example, here is configuration of one package that's not on Melpa, and can be easily upgrade via `quelpa-upgrade`, without writing the recipe in again somewhere.

``` elisp
(use-package multiclip
  :quelpa (multiclip
           :fetcher github
           :repo "kiennq/highlight2clipboard"
           :files (:defaults "bin"))
  :defer t
  :diminish
  :functions (multiclip--normalize-data)
  :init
  (advice-add-once interprogram-cut-function
                   :after (lambda (&rest _) (require 'multiclip)))
  (advice-add-once interprogram-paste-function
                   :after (lambda (&rest _) (require 'multiclip)))
  :config
  (cond
   ;; WSL2 is different machine, so we have to get the host ipaddress for it.
   ((eq system-type-ext 'gnu/wsl)
    (setq multiclip-host
          (substring (shell-command-to-string "ip r l default | cut -d\\  -f3") 0 -1))))
  (multiclip-mode))
```

**Comment by steckerhalter** [comment]
You can use multiple entries in `quelpa-melpa-recipe-stores`, even recipe lists instead of directories with recipes. The default looks like this (melpa recipe directory):

```elisp
(defcustom quelpa-melpa-recipe-stores (list (expand-file-name
                                             "recipes"
                                             quelpa-melpa-dir))
...
```

The idea is that you can use your own recipe stores. Melpa ist just the default. So you can choose to have your recipes in a personal store (and then just invoke `(quelpa 'foobar)` in the init file). Then it's easy to upgrade individual packages as @tsuu32 does it. 

When you use the prefix `C-u` with the `quelpa` command forces an upgrade (it overrides the default) `quelpa-upgrade-p`. It works on any quelpa invocation, so with `M-x quelpa` it upgrades the associated package/recipe (from the store with the highest prio). When you use it on a quelpa expression somewhere it upgrades that package.

The idea of the quelpa cache was that one can upgrade all installed packages easily. It's true that this last change breaks the original behavior and people could get confused. @kiennq could you add an entry on top of the NEWS section documenting the change?

An idea I had now is this: If there would be a way upgrade all packages from the recipe stores then the quelpa cache wouldn't be needed to upgrade all packages. So it would go through the stores and upgrade every installed package.

Of course this is a very different way of using quelpa. If you want to have your recipe definitions together with `use-package` then you probably want/need the quelpa cache feature.

**Comment by tsuu32** [comment]
> No, it's just inconvenient. Normally I expected that all package installed via quelpa can be upgrade without having write the recipe again somewhere.
For example, here is configuration of one package that's not on Melpa, and can be easily upgrade via quelpa-upgrade, without writing the recipe in again somewhere.

I understand.😄
Thank you.

**Comment by steckerhalter** [comment]
is this ok? can we close the issue?

**Comment by tsuu32** [comment]
ok.
I close this issue.
