### ISSUE TITLE
Maintenance question

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#164]
@alphapapa @kiennq 
Does someone of you want to be like the "official" maintainer?

I can work on quelpa sometimes and since you participate I'm also more motivated to do it :smile: 
But all in all I guess I wouldn't do a good job as the maintainer since I've got too many other things to attend to with higher priority for myself.

**Comment by alphapapa** [comment]
I'm willing to consider that.  Would you be a bit more specific about what arrangement you have in mind?

**Comment by steckerhalter** [comment]
Thanks. Yeah well, it would be nice to have someone who takes care of quelpa, like to make it match new versions of Emacs, phase out old stuff, add features if possible and whatever is necessary to keep software current and relevant instead of at a standstill as it was before...

That would also mean to make decisions about further development, if PRs should be merged or not, deciding on change requests and so on.

**Comment by alphapapa** [comment]
Well, I do want Quelpa to continue to be relevant and useful, because I use it myself, and I recommend it as a way to install my packages as well.  So I'm willing to adopt it.  :) 

I would say, similar to how I adopted Outshine, that I will fix bugs and compatibility issues as they come up, make improvements as seems wise (as I have time), and integrate other developers' work as they may offer it.  I will uphold the package's technical excellence and adherence to common conventions and standards, to make it easy for users and contributors.  And I will try to keep the package in good shape for the next maintainer, whoever that might be someday.  I think of it sort of like gardening: keep the weeds pulled, and welcome new plants and gardeners, ensuring that they fit in well.

How does that sound?

**Comment by steckerhalter** [comment]
Nice! I'd say then we have a good way forward... thanks.

**Comment by alphapapa** [comment]
@steckerhalter To ensure we're on the same page: What do you intend your role to be from now on?  Do you intend to keep ownership of the GitHub organization and repo?  

I see that there are 4 of us in the organization now (and I don't know who vyp is).  Is anyone in charge?  Not that I foresee disputes, but it would be good to be clear up front about expectations.

Responsibilities are also important to be clear about.  Am I taking sole responsibility for the project's code?  Who has commit rights?

I want to be clear about these things before I agree to be responsible for anything.  :)

Thanks.

**Comment by steckerhalter** [comment]
@alphapapa I'd say I make you an admin and so you can manage anything if necessary. Then you would be in charge until you need/want help. The others that are still members of the org have not participated for a long time so I don't think we need address this specifically.

**Comment by steckerhalter** [comment]
@kiennq would you like to to act as "deputy" maintainer in case @alphapapa is on holidays or something?
or another possibility would be that you both are co-maintainers and the deputy role changes from time to time

**Comment by kiennq** [comment]
Sure it would be fine to me. Normally I will approve (or reject) then wait for @alphapapa for a day.
@alphapapa please drop a line when you're available (not available) in those cases.

**Comment by alphapapa** [comment]
A day is a very short time to wait for feedback on a PR.  I have quite a few active projects on GitHub, and I don't get to all of them every day.

To be honest, I'm not interested in being a co-maintainer with @kiennq, nor in some kind of "revolving deputy" arrangement.  That sounds like a recipe for conflict.  Our development styles have already been shown to be quite different, and having authority or responsibility pass back and forth, or having code merged while the other is busy, would not be good for the project's code or the maintainers' relations.

And I'm not going to be posting daily updates about my personal life and my expected response time.  This is one project among many, and it's not even updated that often.

@steckerhalter If you want me to maintain Quelpa--and by that I mean, if you want me to take responsibility for it--then I'd ask that you transfer the repository to my account for the duration of the time that I am responsible for it.  I would consider that to be my "adopting" the project as my own (which, to be clear, is not to say "taking credit for the project as my own work") for a period of time, as I have with Outshine, Outorg, and Navi when I adopted them from Thorsten Jolitz.  If later I decided I did not want to be responsible for it anymore, I would offer the repo back to you, or to someone whom you approve of, to adopt it again.

If that's not what you want to do, that's perfectly fine--it's your project, so it's your decision.  In that case, I'll probably maintain a personal fork for my own use.

Let me know what you want me to do.

Thanks.

**Comment by steckerhalter** [comment]
@alphapapa what you mean by "transferring the repo to your account"? this repo is part of the quelpa org and not connected to an individual account.

**Comment by steckerhalter** [comment]
Well, in general I'd say what I have in mind is a consensus-based maintainership. Quelpa is not a project that needs a whole lot of work, but work can be done and if people work together to try to find consensus it's often beneficial for everyone. As quelpa is an org there is no adoption in this sense, but people can commit to fulfill a certain role in the org for a certain time and I'd prefer to have more people working together on this project than to have just one person being "in charge" or not.

**Comment by alphapapa** [comment]
@steckerhalter Of course, I respect your decision to run the project as you see fit, and I'm thankful for your work on it.  It's an invaluable part of my Emacs config, and I recommend it extensively in my packages' documentation.

I think that consensus-based maintainership can work well in the right circumstances, however I don't think that's the case at the moment here.  I hesitate to criticize @kiennq too harshly, but some of his recent activity here may illustrate what I mean.

* https://github.com/quelpa/quelpa/pull/155  After all the feedback we gave, he closed the PR without merging it and without explanation.
* #166 He now opens a new PR.  He says that it deprecates #155, but he doesn't explain how or why.  As a reviewer and co-maintainer, I have no idea if the feedback given on #155 is addressed by it, because the new PR is disconnected from that feedback.
* In spite of the fact that I have repeatedly asked him to make small commits with a single purpose, this new #166 claims at least 3 distinct purposes:

1.  > Allow quelpa to install recipe from quelpa-cache as preferred recipe.
2.  > Also make quelpa-upgrade to only show upgradable (installed) packages.
3.  > This will make #155 deprecated.

* However, he omitted a fourth purpose of the PR: he added a `.editorconfig` file without explanation or comment.
* AFAICT the new PR does not even address #166's purpose.  So what happened to those changes?  Did he change his mind?  Is he going to sneak them in in other commits?

At this point, I don't know if these issues are a matter of carelessness or of intentionally disregarding what's been asked of him.  In the end, it doesn't matter: it is disrespectful of our time as co-maintainers to continue doing these things.

In the context of this discussion, he's now said that he will merge changes if I don't respond within one day.  So if he keeps his word about that, and if he continues the pattern of behavior he's demonstrated, that means that he will make these kinds of careless changes, leaving us (or me?) to either clean up after him or allow the quality of the project to decline.

I simply have better things to do with my time than deal with that.  I am willing to help oversee and develop the project, reviewing and merging changes proposed by others as I have time.  I am not willing to serve as co-maintainer on an equal basis with someone who continues to act this way.

I hope you understand my position.  Again, I appreciate your work, and I'll respect your decision to run your project as you see fit.  If I need to maintain my own personal fork, I'll do that with no hard feelings, and I'll be glad to contribute patches now and then if appropriate.

Please let me know what you want me to do.  Thanks.

**Comment by steckerhalter** [comment]
Thank you for your answer. I appreciate your aim to keep the quality of the project high. Since there seems to be a bit of a conflict brooding here now I'd suggest that I review the changes from @kiennq and we can discuss the maintenance question another time.

It seems that there are people using quelpa and I wasn't aware of that really until we moved back to Github (thanks to your suggestion). Would it be possible that you merge the CI branch so we can have that in master? I think it would be good if we could move away from Travis.

If you think a fork is necessary I'd be happy if you could give feedback on things that you would like to see changed here or make PRs so we can keep it aligned.

Thanks.

**Comment by kiennq** [comment]
Thanks for your advise @alphapapa.
I'm not trying to be disrespectful here and also highly appreciate your aim of keeping quality of project.
I will just share my 2c here



> * #155  After all the feedback we gave, he closed the PR without merging it and without explanation.
> * #166 He now opens a new PR.  He says that it deprecates #155, but he doesn't explain how or why.  As a reviewer and co-maintainer, I have no idea if the feedback given on #155 is addressed by it, because the new PR is disconnected from that feedback.

As I said in a comment of #166, that PR is deprecating #155. The purpose of them are the same, to make user to not accidently upgrading (or even see) the uninstalled package.
That's why with #166, I close #155 without merging. The two PR take different approach, and with the state of #155, I don't see it qualified for merging.


The sole purpose of doing side project is for fun, to relieve stress from already accumulated over from work.
I know that we have different standards, for me just have the travis passed and the code looks clean is already a pass. I you're prefer having higher ones, you can share, as a guide line, it will make it much easier for other to contributing to this project too.

Just to be clear here, I'm really appreciate your aim of keeping project with high quality. So that's why I said I will wait for your response, maybe like for a day. In my work environment, and projects that I contributed to, the pace is fast, a day is more than enough to drop a line like: "Let's me take a look" or so. If you think that's not enough, it's always easy to just say "Wait until I review the change to merge it".
You don't even let me to voice my response but come straight to criticize me, which's I don't think it's respectfully at all.

Anyway, thanks for your advices.

**Comment by alphapapa** [comment]
@steckerhalter Ok, I've merged the branch.  CI passes back to Emacs 25.1, e.g. https://github.com/alphapapa/quelpa/actions/runs/47113952  Note that elpa.gnu.org is giving intermittent Bad Request errors lately, and those can cause intermittent CI failures.

**Comment by steckerhalter** [comment]
@alphapapa thanks! there been connectivity issues with elpa.gnu.org since the beginning so I'm used to that :smile:

**Comment by alphapapa** [comment]
@steckerhalter Do you plan to continue discussing the maintenance issue, or are you satisfied with the current situation?

**Comment by steckerhalter** [comment]
@alphapapa no, I think it's alright like this. Thanks to you and the move to Github I realized that people still use quelpa and I don't want to abandon it anymore now :wink: 

Of course I'd be glad if you guys can help me out a bit if I should lag behind because of my RL :smile:

**Comment by alphapapa** [comment]
Ok.  Thanks for your work.

**Comment by steckerhalter** [comment]
Thank you too

**Comment by jcs090218** [comment]
hmm... I have left the comment [here](https://framagit.org/steckerhalter/quelpa/-/issues/171), but I somehow forgot about this.

@steckerhalter Would you mind adding me as another maintainer? I would like to co-maintain this package mainly because my config heavily depends on this. Thank you and thanks your awesome work!

**Comment by steckerhalter** [comment]
@jcs090218 yeah sorry I'm late with answering... I'll add you

**Comment by jcs090218** [comment]
@steckerhalter Sorry for bothering you! You are not late for answering! I am just worry that I may forgot about this again!

Anyway, thank you very much! 😄
