### ISSUE TITLE
quelpa-upgrade has no effect after switching branch with older commit

### ISSUE THREAD

**Issue by wyuenho** [quelpa/quelpa#186]
Reproduction:
1. Put this in .emacs
```elisp
(use-package window-purpose
  :quelpa (window-purpose :fetcher github :repo "wyuenho/emacs-purpose" :files (:defaults "layouts")
                          :branch "improve-code1-emacs27-recursive-load-temp-fix")
```
2. Start up emacs
3. M-x quelpa-upgrade RET window-purpose RET
4. Change branch to `"improve-code1"`
5. Restart emacs
6. M-x quelpa-upgrade RET window-purpose RET
7. Notice package timestamp is still the timestamp of `improve-code1-emacs27-recursive-load-temp-fix`'s latest commit.

Expectation:
Switching branch should checkout the latest commit from that branch and put it into `~/.emacs.d/elpa/`, regardless of whether its latest commit is older than what currently in `~/.emacs.d/elpa/`.

**Comment by steckerhalter** [comment]
When I install this:

```cl
(use-package window-purpose
  :ensure nil
  :quelpa ((window-purpose :fetcher github :repo "wyuenho/emacs-purpose" :files (:defaults "layouts")
                           :branch "improve-code1-emacs27-recursive-load-temp-fix") :upgrade t))
```

I end up getting: `window-purpose-20200328.937`

which is weird because the time stamp should be 2019:

```
commit 2bf4ed270a42aaca07c9218519d63409b14ac666 (grafted, HEAD, origin/improve-code1-emacs27-recursive-load-temp-fix, improve-code1-emacs27-recursive-load-temp-fix)
Author: Jimmy Yuen Ho Wong <wyuenho@gmail.com>
Date:   Sun Nov 17 23:04:08 2019 +0000
```

I don't know yet why it happens

**Comment by steckerhalter** [comment]
20200328.937 is the time stamp from the other branch `improve-code1`

**Comment by wyuenho** [comment]
The timestamps are correct. They are commit times, not author times. It's quelpa that isn't correctly handling them by switching branches in the local clones, comparing correctly and replacing the packages in `package-user-dir`

**Comment by steckerhalter** [comment]
alright. @kiennq do you have time to take a look what's going on here?

**Comment by kiennq** [comment]
> 1. Put this in .emacs
> 
> ```emacs-lisp
> (use-package window-purpose
>   :quelpa (window-purpose :fetcher github :repo "wyuenho/emacs-purpose" :files (:defaults "layouts")
>                           :branch "improve-code1-emacs27-recursive-load-temp-fix")
> ```
> 
> 1. Start up emacs
> 2. M-x quelpa-upgrade RET window-purpose RET
> 3. Change branch to `"improve-code1"`
> 4. Restart emacs
> 5. M-x quelpa-upgrade RET window-purpose RET
> 6. Notice package timestamp is still the timestamp of `improve-code1-emacs27-recursive-load-temp-fix`'s latest commit.

There're two issues here:
1. `Quelpa` doesn't support to upgrade to older version. As `improve-code1` has older timer than `improve-code1-emacs27-recursive-load-temp-fix`, when you run `quelpa-upgrade` it will not downgrade to that.
2. How did you change branch to `improve-code1`? 
If you change it by `git checkout` in cloned repository folder under `quelpa-build-dir`, then `quelpa-upgrade` will not help you with that.
By design, `quelpa-upgrade` will only upgrade to what recorded in your receipt, that means only upgrade to latest version of `improve-code1-emacs27-recursive-load-temp-fix` (with caveat of (1)).
If you want to upgrade to the version that's currently checked-out, you can use `C-u C-u M-x quelpa-upgrade`.

@steckerhalter Do you know why we don't support (1)? I.e., down grading to older package version?

**Comment by wyuenho** [comment]
> How did you change branch to improve-code1?

I'm using `use-pacakge-quelpa`, I just changed the `:branch` value in the recipe.

To me, upgrade means upgrading from whatever is installed by package.el, so I'd expect this case to work. If there's already a clone locally, quelpa should simply do a fetch and check out the requested branch.

**Comment by kiennq** [comment]
> To me, upgrade means upgrading from whatever is installed by package.el, so I'd expect this case to work.

No, it's not like that. Upgrade here means upgrade to newer version, same meaning with upgrade by `package.el`, i.e., from `list-packages`.

**Comment by steckerhalter** [comment]
@kiennq yeah well, I'd say the whole point of `upgrading` always was that and not to downgrade so the whole logic is built around this concept, comparing version numbers if the requested version is higher than the current version etc.

I guess to make it possible to switch to any version, the code would have to be changed substantially and also "upgrading" wouldn't make sense for such an action. Usually the user doesn't want an older version to replace the current version so it would have to be a special command or switch.

**Comment by kiennq** [comment]
@wyuenho, with #187 you can
- go to cloned package repositories under `quelpa-build-dir`, 
- switched to your development branch and upgrade to it with `C-u C-u M-x quelpa-upgrade`.

**Comment by wyuenho** [comment]
@kiennq that's what I did, doesn't mean this isn't a bug tho.

**Comment by kiennq** [comment]
> that's what I did, doesn't mean this isn't a bug tho.

That would be more like a feature request to me.
Up until now, Quelpa only support upgrade to newer version. So, even if you change the branch in your recipe, it will not downgrade to that. It does checkout to the latest commit in your branch in cloned repository though.
This is done since you can upgrade your package to MELPA version via `package.el` too. We don't want to overwrite user package in that case.

However, to support the easy to develop package when using Quelpa, I think it's beneficial to add #187, which is a slightly different route.
- You can go to clone repository and checkout branch / make changes to that.
- Then you can use `C-u C-u M-x quelpa-upgrade` (that means upgrade to local ref), and it will overwrite your installed package with whatever in the repository folder, even downgrading.

**Comment by kiennq** [comment]
@wyuenho Do you think #187 is sufficient for your case? I.e., you can use `C-u C-u M-x quelpa-upgrade` to upgrade to local checkout branch, regardless of current installed version.

**Comment by wyuenho** [comment]
This works for me, thanks
