### ISSUE TITLE
Install as installed and not dependency

### ISSUE THREAD

**Issue by jcs090218** [quelpa/quelpa#199]
Right now when I install a package through quelpa; the package itself is mark as `dependency` yet is not. Is there a way to avoid this and instead just mark it as `installed` and not `dependency`? 😕 

Thanks!

**Comment by kiennq** [comment]
@steckerhalter.

**Comment by tsuu32** [comment]
If `package--user-selected-p` of the package is non-nil, the package is marked as `installed`, otherwise `dependency`.
In my environment `(package--user-selected-p 'company)` returns non-nil, so `company` is marked as `installed`.

I don't know when `quelpa` (or package.el) sets`package-selected-packages` variable.

**Comment by jcs090218** [comment]
I usually let the `package.el` decide weather a package should be a `dependency` or `installed`. I think the default action is to install it as a `installed` and not `dependency`? And then at any time later if `package.el` find out the package is actually a `dependency` then it will change as it.

**Comment by tsuu32** [comment]
>  I think the default action is to install it as a installed and not dependency? And then at any time later if package.el find out the package is actually a dependency then it will change as it.

Is this true?

In my environment, 
package.el:
Installing `dash` and then installing `magit`, `M-x list-packages` says `dash` and `magit` are `installed` and others (such as `transient`) are `dependency`.

quelpa.el:
Installing `dash` and then installing `magit`, `M-x list-packages` says all (such as `dash`, `magit` and `transient`) are `installed`.
(That's because `qeulpa` use `package-install-file` to install packages including dependencies.)

Anyway if `package-selected-packages`'s value is not saved in init file, package status will be broken.

**Comment by jcs090218** [comment]
> In my environment,
package.el:
Installing dash and then installing magit, M-x list-packages says dash and magit are installed and others (such as transient) are dependency.

Yeah, I think I did not express correctly in the last but yes, this is what I mean when package.el find out the dependency!

> quelpa.el:
Installing dash and then installing magit, M-x list-packages says all (such as dash, magit and transient) are installed.
(That's because qeulpa use package-install-file to install packages including dependencies.)

Cool, in my case, this is totally opposite. They all installed it as a dependency no matter if the package is dependency or not! 😕 

Can anyone explain this to me? Thanks!

**Comment by tsuu32** [comment]
Please check `package-selected-packages`‘s value.

**Comment by jcs090218** [comment]
> Please check package-selected-packages‘s value.

Yes, the new installed package through `quelpa` is not added by default. At least on my end, that is the result.

**Comment by steckerhalter** [comment]
sry, I'm absorbed with RL... probably will have time in a few days...

**Comment by kiennq** [comment]
@thierryvolpiatto as he can provide advices about `package.el`

**Comment by thierryvolpiatto** [comment]
kiennq <notifications@github.com> writes:

> @thierryvolpiatto as he can provide advices about package.el

Each package user install explicitely e.g. M-x package-install foo is
considered as an installed package i.e. it is added to
package-selected-packages.
If later you install another package that use it as dependency, it is
still considered as an installed package i.e. it stays in
package-selected-packages but if you want to delete it, package.el will
notice it is also a dependency and refuse to delete it.
At least it is how package.el should work (it was so when we introduced
package-selected-packages).
For package upgrade package.el is upgrading i.e. compiling+loading
package and dependencies in a random order which is wrong and lead to
horrible bugs in packages, dependencies should be upgraded first.
See helm-elisp-package.el for example.
Can't tell you more as I don't use and know quelpa.

HTH.

-- 
Thierry

**Comment by steckerhalter** [comment]
please reopen if this is still an issue
