### ISSUE TITLE
Partial cloning requires very recent versions of git

### ISSUE THREAD

**Issue by cubranic** [quelpa/quelpa#218]
For instance, `--filter=blob:none` was added in git v2.20, which was released in late 2018, so would only be available in the most recent Ubuntu LTS. Centos lags even further behind: Centos 7 includes only Git v1.8. It would be nice if `quelpa` detected such installations and either printed a warning message to the user or automatically fell back to setting `quelpa-git-clone-partial` to `nil`.

Or, at the very least, mention the git version consequences in the Prerequisites section of Readme.

**Comment by kiennq** [comment]
I would definitely recommend to upgrade to latest Git version if possible since old Git client can contains some very serious security [bugs](https://www.cvedetails.com/vulnerability-list/vendor_id-15815/product_id-33590/Git-scm-GIT.html)
Will add the mention in prerequisite and some code to check for git version.

**Comment by cubranic** [comment]
Thank you!
