### ISSUE TITLE
cache contains duplicates

### ISSUE THREAD

**Issue by steckerhalter** [quelpa/quelpa#69]
```cl
((scss-mode :repo "antonj/scss-mode" :fetcher github)
 (anzu)
 (aes)
 (darktooth-theme)
 (noctilux-theme)
 (magit :fetcher github :repo "magit/magit" :commit "1.4.0")
 (magit :fetcher github :repo "magit/magit")
 (magit :fetcher github :repo "magit/magit" :files
        ("magit.el" "magit-bisect.el" "magit-blame.el" "magit-key-mode.el" "magit-popup.el" "magit-wip.el" "magit.texi" "with-editor.el" "AUTHORS.md" "README.md"))
 (ein)
 (magit :repo "magit/magit" :branch "next" :fetcher github)
 (outorg-export)
 (outorg)
 (sqlformat :fetcher github :repo "steckerhalter/sqlformat.el")
 (org-caldav)
 (org-caldav :repo "dengste/org-caldav" :fetcher github :files
             ("org-caldav.el"))
...
```

only one recipe should be left in the cache for a package and the others removed

**Comment by wasamasa** [comment]
The problem lies within the use of `add-to-list` for adding the expanded recipe of the last package installed unconditionally to the cache.

It would be better if the `quelpa` function would first search for occurrences of the recipe to be added with something like `cl-find` by its `car`. If it doesn't find such a thing, it should `push` the new element into the list. If it finds such a thing, it should use `cl-substitute` to replace that value with the new one. Alternatively, it could use `cl-remove` to delete the matching item, then `push` the new one to the beginning of the list. The latter option would allow to reuse the code as needed for the alternative branch.

**Comment by steckerhalter** [comment]
sounds good to me, maybe the second option is cleaner?

**Comment by wasamasa** [comment]
Apparently, using `cl-find` isn't even necessary for this.

**Comment by wasamasa** [comment]
As #70 is merged, I'm closing this.
