### ISSUE TITLE
Revisit bootstrapping

### ISSUE THREAD

**Issue by wasamasa** [quelpa/quelpa#76]
IIRC the current bootstrapping method was chosen to both conform to [el-get](https://github.com/dimitri/el-get#the-lazy-installer) and because [MELPA's package-build](https://github.com/milkypostman/melpa/blob/master/package-build.el) library wasn't available as standalone package. Can this design decision be reconsidered now that [package-build](https://github.com/milkypostman/melpa/blob/master/recipes/package-build) is on MELPA and people who have already configured MELPA as their package archive could be installing Quelpa from there instead of copy-pasting the bootstrap script and evaluating it?

Also, are there any downsides to this approach? What about the self-upgrading part, would that still work with the dependencies installed from MELPA?

**Comment by vyp** [comment]
> Also, are there any downsides to this approach? What about the self-upgrading part, would that still work with the dependencies installed from MELPA?

That's what I was thinking, I have this:

``` elisp
(if (require 'quelpa nil t)
    (quelpa
     '(quelpa
       :fetcher github
       :repo "quelpa/quelpa"))

  (with-temp-buffer
    (url-insert-file-contents "https://raw.github.com/quelpa/quelpa/master/bootstrap.el")
    (eval-buffer)))
```

(instead of `(quelpa-self-upgrade)` as it says in the readme) in my .emacs which seems to update quelpa too using itself when doing `quelpa-upgrade`. And ideally I do not even want to temporarily (or initially) rely on MELPA to install quelpa.

It's not that I have anything against melpa or even think it's "unreliable" or whatever, it's that being able to *not depend on* melpa should be the "ideal" that quelpa should try for, in my opinion. Because quelpa is supposed to be about building packages on the fly and directly from source. For e.g. one use case for quelpa is that you don't have to wait for melpa to build a new revision of a package, to use that package.

(You [already know this](https://www.reddit.com/r/emacs/comments/21oo98/quelpa_is_emacs_crack_ie_why_was_this_not_posted/cgf3tq5) of course.)

(I also have `(quelpa 'package-build)` in my .emacs so that quelpa upgrades melpa's package-build too. Not sure if that's the correcty way to do things though.)

**Comment by wasamasa** [comment]
Hmm, I didn't formulate this as clearly as I should have.  I'm in favour of providing an alternative installation method alongside the current one.  This would both solve the issue of bootstrapping looking like something from http://curlpipesh.tumblr.com/ and make it simple to get started for MELPA users.

**Comment by vyp** [comment]
Yes if it's just an additional method that utlises the melpa package-build package for installation, I don't see anything wrong with it. Quelpa will update package-build from then on anyway right? So it *shouldn't* cause any self-upgrade issues correct?

**Comment by steckerhalter** [comment]
I think at the time quelpa was started package-build.el had a dependency on another file (json-something...) in the melpa repo so I thought it's safest to just fetch the package-build `tar` from melpa.milkbox.net and install that.

In the meantime the dependency was dropped and just `package-build.el` is enough so bootstrapping *could* be made simpler by doing something like @vyp does

The problem with this approach is that if upstream decides to refactor package-build and split it up or something that method would fail.

As for using MELPA to install quelpa, I think that should work ok. I don't think there should be any conflict with packages from MELPA but that would have to be tested to make sure.

**Comment by vyp** [comment]
Yes I agree, I just realised if package-build changes upstream to require other packages, simply doing something like loading it temporarily will still fail. i.e. it doesn't scale.

@steckerhalter Although do notice that what I have loads in bootstrap.el as normally suggested in the readme if quelpa isn't already installed. I only mentioned that because it means I don't have to do `quelpa-self-upgrade` (`quelpa-upgrade` seems to upgrade quelpa too). So it *still* uses melpa for package-build because bootstrap.el uses melpa for it if I understand correctly.

---

Anyway, that's only part of what @wasamasa opened this issue for I think. I think he mainly means to use the melpa package instead of the downloading the tar in bootstrap.el or something? Or is it that there's no need for bootstrap.el at all anymore? Although quelpa isn't on melpa so isn't *some* form of bootstrapping always required?

This has sort of always been the case with *package managers*, because the job of a package manager is to install packages and such, but the problem is always how does it install itself? (I'm talking about system package managers here, because things like npm, pip, and such never need to worry about installing themselves, obviously.)

So I agree with @wasamasa, I [hate](https://www.seancassidy.me/dont-pipe-to-your-shell.html) the `curl | sh` paradigm too, and using the melpa repository seems like one of the only reliable and future-proof methods to install package-build (in case it changes its dependencies).

---

Sorry this comment became way too long for saying essentially nothing.

**Comment by steckerhalter** [comment]
@vyp yes, boostrap.el fetches package-build from the melpa package-archive and installs that via `package-install-file`

`quelpa-self-upgrade` is:

```cl
(defun quelpa-self-upgrade (&optional args)
  "Upgrade quelpa itself.
ARGS are additional options for the quelpa recipe."
  (interactive)
  (when (quelpa-setup-p)
    (quelpa (append quelpa-recipe args) :upgrade t)))
```

so essentially it's what you have in your config. the reason I put it into a function is that we can change it if it should be necessary where otherwise it's hard coded in the user's config

**Comment by wasamasa** [comment]
So, does that mean it's sufficient to add Quelpa to MELPA and extend the installation instructions to mention installing Quelpa from MELPA as an alternative to the current bootstrapping method?

**Comment by steckerhalter** [comment]
Yes, I think so. Probably a sane way to do it would be:

1. add to MELPA
2. add some tests that bootstrap using MELPA
3. make some tests locally to check for possible issues
4. if everything works: add instructions

**Comment by steckerhalter** [comment]
so the first step is done: http://melpa.org/#/quelpa

**Comment by zakame** [comment]
For the record I now obtain quelpa through quelpa-use-package, with no issues:

```emacs-lisp
(use-package quelpa-use-package
  :ensure t
  :config
  (setq quelpa-checkout-melpa-p nil))

;; fetch my own version of ido-other-window
(use-package ido-other-window
  :quelpa (ido-other-window :fetcher github :repo "zakame/ido-other-window"))
```

**Comment by steckerhalter** [comment]
@zakame great, you did it! :smile:

**Comment by steckerhalter** [comment]
quelpa is in melpa for quite a while now
