### ISSUE TITLE
Asking for information about Quelpa capabilities

### ISSUE THREAD

**Issue by syl20bnr** [quelpa/quelpa#93]
We have integrated Quelpa into Spacemacs, I open this issue in hope to save some time to gather what need to be done in Quelpa to support Spacemacs requirements.

1- Does Quelpa support fetching a specific branch of a git repo ? A specific commit ?
2- Does Quelpa support package dependencies ?
3- Is Quelpa already providing an ELPA archive file ?

Thank you for Quelpa and for taking time to answer my questions.

**Comment by vyp** [comment]
1. Yes.
2. Yes.
3. Not sure (wait for quelpa devs to answer).

**Comment by vyp** [comment]
https://github.com/milkypostman/melpa/#recipe-format is how to get a specific branch/commit.

For dependencies, the `;; Package-Requires:` line is used. Currently these dependencies have to be on MELPA because quelpa will fetch the MELPA recipe for a package to build it.

**Comment by wasamasa** [comment]
@syl20bnr Quelpa uses `package-build.el`.  Therefore, it supports anything that library supports, including checking out specific Git branches and commits.  Package dependencies can be grabbed automatically if they are present on MELPA, otherwise you'd need to have them installed beforehand from whatever other place they come from.  Regarding the last thing, this sounds like you're misunderstanding what Quelpa's purpose is.  It is a tool for building and installing packages, not providing an ELPA mirror.  For that you're better off with either simple HTTP servers doing this already (like [elpa-mirror](https://github.com/redguardtoo/elpa-mirror) or [servant](https://github.com/cask/servant)), bypassing this completely by just pointing to [a local directory](https://www.gnu.org/software/emacs/manual/html_node/elisp/Package-Archives.html) or using Quelpa to not fetch prebuilt packages in the first place.

**Comment by syl20bnr** [comment]
Thank you for your answers.
If a package X is not on MELPA but its dependencies are on MELPA, Quelpa will fetch them from it, am I right ?
In the case where X depends on Y and both are not on MELPA then Quelpa won't fetch Y, is this correct ?
The correct way to handle the second cases is to install Y before X which makes sense because someone as to provide a recipe for Y anyway.

From the MELPA recipe doc it seems that nested recipes for dependencies are not supported, does Quelpa recipes have this support ? If not, are you open for such feature or do we keep this in Spacemacs only ?

**Comment by vyp** [comment]
1. Correct.
2. Correct.
3. Correct.
4. I don't think you should need nested recipes. You should be able to just specify the dependency's recipe beforehand (if you want a custom recipe not on MELPA that is). I'm not a quelpa dev, but in my opinion, nested recipes seem like an ugly way to handle things.

**Comment by syl20bnr** [comment]
Thank you for the quick answers.
Nested recipes allow to keep things tied together instead of listing package dependencies as they were stand alone packages. It forces to put a comment on package dependencies if we don't want to forget about it in a few months :-)
We can handle it on the Spacemacs side so no big deal if Quelpa maintainers are not interested by this feature.

**Comment by vyp** [comment]
In my opinion, you should be able to just specify recipes without worrying about the dependency tree, which package-build/quelpa should deal with *for you*. However, I also understand that having to specify a dependency's recipe before the actual package's recipe as I said in the previous comment is also related to worrying about the dependency tree.

A possible solution here may be https://github.com/quelpa/quelpa/pull/91, which, if merged, will bring an option to specify more custom directories full of your own recipes (just like to your own version of https://github.com/milkypostman/melpa/tree/master/recipes). This way, you can specify whatever custom recipes you want in these such a directory. And then when you do `(quelpa 'X)` to install a package named `X` which depends on package `Y`, quelpa will install `Y` first (provided you have `;; Package-Requires: (Y <version-number>)` in the source code for `X`), before installing `X`, provided you have the recipes for these packages in your custom recipe directory. This also goes for nested dependencies (i.e. any dependencies of package `Y`, provided of course you have their recipes and the appropriate `;; Package-Requires:` line in `Y`).

And if you don't have the recipe for a particular package in your custom recipe directory, it will fallback to the default MELPA recipe list to get a recipe, so you don't have to replace everything, only the recipes you want to customise.

**Comment by syl20bnr** [comment]
After reading your message it seems to me that my request is Spacemacs specific. The way packages and recipes are declared in Spacemacs make the approach you describe not ideal. But the approach described fit perfectly with Quelpa and address the dependency issue really well for any non Spacemacs users of Quelpa.

**Comment by vyp** [comment]
Ah I don't know anything about how packages are handled in spacemacs, mind explaining how it works? Also I want to reiterate that nothing I say is final, I'm not a quelpa developer, and it is all just in my opinion. 

FWIW I recently switched my emacs config to work with a custom recipe directory option as #91 provides, if you want to see what I mean: https://github.com/vyp/ui/tree/8df945749080f7d80b139c0744dd2bc883382fbd/emacs/.emacs.d/recipes. There's not that many packages there because I am new to emacs and still learning about lots of emacs things/packages. (I'm not using spacemacs.)

**Comment by syl20bnr** [comment]
In spacemacs we have a list of packages with keywords:

Fetch from ELPA repos:
```elisp
(setq package-list '(my-package))
```

Local package on disk:
```elisp
(setq package-list '((my-package :location local)))
```

Fetch from a github repo:
```elisp
(setq package-list '((my-package :location (recipe :fetcher github :repo xxx)))
```

Now if we want dependencies it is just a matter of adding a keyword argument:
```elisp
(setq package-list '((my-package :location (recipe :fetcher github :repo xxx) :deps ((Y :fetcher....)))
```

**Comment by syl20bnr** [comment]
Note that we don't want to use Quelpa recipe everywhere, this is why we have `local` location (which obey a given structure of what we call `layers`). Layers in Spacemacs are both plain dumb and very expressive, we are able to make hundreds of packages configuration live well together with it.

**Comment by vyp** [comment]
This is some pretty interesting stuff. Especially about how you want to list a package and its dependencies as a single group.

> Now if we want dependencies it is just a matter of adding a keyword argument:

I'm not following, isn't a dependency of a package another package that it requires to function? If so, shouldn't the dependencies be specified upstream in `;; Package-Requires` line anyway? Why would a user need to manually specify a dependency?

Or is it simply because you want to 'group' them? If so, why not just 'group' them automatically (somehow...), instead of making the user do it?

**Comment by syl20bnr** [comment]
We have to provide Y location anyway right ? And I don't want it to appear explicitly in the package-list because we don't configure it.

**Comment by syl20bnr** [comment]
Remember that Y is not in MELPA.

**Comment by vyp** [comment]
You probably already know this, but it may be worth mentioning that el-get supports a `:depends` keyword in its recipes. Of course, el-get is a different system from quelpa altogether, so I cannot help much further with that.

> And I don't want it to appear explicitly in the package-list because we don't configure it.

If I understand correctly, spacemacs has some sort of custom list-packages function (assuming `M-x list-packages` cannot already do this), in which you want to list only the 'top-level' packages (i.e. all the packages installed specifically by the user, as opposed to being installed because it's a dependency)? And if a particular dependency package has been configured, it is also given a listing in this list, even though it was installed as a dependency?

And is listing packages the only reason you want to be able to group packages?

**Comment by syl20bnr** [comment]
Actually people manipulates layers instead of packages (there is also the possibility to add directly a package). Each layer has its own package list where only configured packages are listed. Dependencies are handled by packages.el but in this particular X and Y use case we need a way to express these deps ourselves.

**Comment by vyp** [comment]
Ah I see, a bit more complicated. This layers approach is a very cool and interesting way to configure things! :)

I guess if you think it's a spacemacs-specific scenario, it would be best to keep this in spacemacs. But really the decision lies with @steckerhalter and @wasamasa. And maybe putting it in quelpa makes things easier for you, or is it mostly the same either way? (sometimes putting a feature upstream makes things much easier for downstream packages)

> Dependencies are handled by packages.el but in this particular X and Y use case we need a way to express these deps ourselves.

Assuming you mean package.el.. AFAIK, package.el is not even that sophisticated when it comes to 'package' management. For example, I don't think it really has an understanding of 'dependencies' does it? I think tools like quelpa handle dependencies for it and handle the order in which things should be built. Even when you delete a package using `M-x list-packages`, the package's dependencies are not deleted, and so you could end up with obsolete packages that were installed as a dependency (but are no longer required). (And it's not that simple, a proper package manager would have to check if any of the dependencies are required by other packages, and so on.)

If I'm correct about that, then maybe the problem here lies partially with package.el? Even judging by this comment of yours https://github.com/milkypostman/melpa/issues/2944#issuecomment-122620030, a lot of the cool things you have implemented here with spacemacs could maybe be helpful higher up like in package.el itself?

**Comment by vyp** [comment]
Ah I see you have already addressed my last point: https://github.com/milkypostman/melpa/issues/2944#issuecomment-131576539.

**Comment by syl20bnr** [comment]
Sorry package.el and not packages.el (which are Spacemacs specific :-)). Actually this is package.el which does the heavy lifting to take care of dependencies, this is even more the case in Emacs 25 where package.el has got a lot of improvement in this regard.

**Comment by syl20bnr** [comment]
More info here: http://endlessparentheses.com/new-in-package-el-in-emacs-25-1-better-dependency-management.html

**Comment by vyp** [comment]
@syl20bnr Thanks for the link, that's exactly what I was complaining about. Good to know it's better in the latest version.

**Comment by steckerhalter** [comment]
@syl20bnr quelpa uses the dependency info in the elisp header, for example: https://github.com/magit/magit/blob/master/lisp/magit.el#L17

if there are any dependencies not available it fetches the recipe from melpa's recipes directory (which is being checked out in quelpa's build directory) and installs them recursively (meaning if a dependency package requires further dependencies it will first install these and so on)

PR #91 by @vyp adds the possibility to customize the path where the recipes are loaded from and you can also use more than one location. I was already thinking that it could additionally lookup the recipes from a list instead of a directory.

manually specifying dependencies is not package.el "compliant" so to say. if you try to install a package with `package-install-file` and the dependency is missing (i.e. it is not installed in .emac.d/elpa) package.el will abort with an error

>  Is Quelpa already providing an ELPA archive file?

not anymore ;)
when I started writing quelpa I was actually using a local archive served via an emacs webserver but then I found out that packages could be installed locally with `package-install-file` which made everything much simpler so I removed that code again

for what would you require such an archive?

**Comment by syl20bnr** [comment]
> manually specifying dependencies is not package.el "compliant" so to say. 

But in the case where X depends on Y and both X and Y are not in any archive then the user has to provide a recipe to specify where to fetch Y.

**Comment by syl20bnr** [comment]
Since I don't use directories of recipes on purpose then reusing the recipe of the root package makes sense to me.

**Comment by steckerhalter** [comment]
> But in the case where X depends on Y and both X and Y are not in any archive then the user has to provide a recipe to specify where to fetch Y.

if you do `(quelpa 'magit)` it will lookup the recipe for magit in the recipes directory (or a variable if that feature was added) and also for all the dependencies

> Since I don't use directories of recipes on purpose then reusing the recipe of the root package makes sense to me.

how do mean "reuse the recipe of the root package"?

**Comment by syl20bnr** [comment]
Doing something like

```elisp
(package :fetcher github :repo foo :deps ((dep1 :fetcher...) (dep2 :fetcher)))
```

Doing this is for the extrem use cases where both `package`, `deps1` and `deps2` are not in any archive and even package could be some random code without the dependencies correctly defined.

I can handle this on the Spacemacs side with a `:deps` new keyword arguments for packages where I first call. Actually this is what I will do because we don't use quelpa 100% of the time so even if Quelpa supported it I would still have to take it out from the root package recipe.

I talk about this implementation in spacemacs where `:deps` is not part of the recipe.
```elisp
(setq package-list '((my-package :location (recipe :fetcher github :repo xxx) :deps ((Y :fetcher....)))
```

**Comment by steckerhalter** [comment]
I see, just as a sidenote, random code that does not have a valid header and footer (according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Packages.html#Simple-Packages) cannot be installed with quelpa ( `package.el` which is used under the  hood to install the built packages also errors out if the format is invalid).

if `(package-buffer-info)` works then the file should be good to go

what I wonder about is how the mechanism in Emacs 25.1 will tell if something is a dependency or not, my guess is that it checks if a package is listed as a dependency somewhere and if that's not the case it is listed as "installed" by the user

**Comment by steckerhalter** [comment]
Looks like this is answered? Otherwise reopen... thanks
