### ISSUE TITLE
automatically install a package even if it's built-in

### ISSUE THREAD

**Issue by bricewge** [quelpa/quelpa#96]
This is a follow up of quelpa/quelpa-use-package#4

I use `quelpa-use-package` for getting `tramp` which is a built-in package of Emacs, so it isn't installed automatically because of it is already present.

Could you add support to automatically install a package from `quelpa` even if it's already present without forcing it to upgrade every time?

**Comment by vyp** [comment]
Basically, I think there needs to be a way to differentiate between a package that's already installed and available from being bundled with emacs, and one that's been installed via quelpa (i.e. package.el). So the distinction from `:upgrade t` is that it doesn't try to install/upgrade if quelpa has already installed it.

Perhaps, is there an api/function to check the list of packages that package.el shows via `M-x list-packages`? Because a simple check in that list might work.

@bricewge has proposed that `:pin` be used for this.

**Comment by vyp** [comment]
Ah right, the status `built-in` vs `installed` can be used.

**Comment by vyp** [comment]
So see the `describe-package` and `describe-package-1` functions...

**Comment by steckerhalter** [comment]
I think quelpa should always prefer the user's package over a built-in one (which is not the case currently). If we make it work like that there isn't even any keyword necessary.

So if you have `org` installed it would check if there is only the builtin version and if so it would go ahead and try to install the user's package.

I can't think of any conflict or problem right now. If I want to install `tramp` I **want** it exactly to override the built-in version.

**Comment by vyp** [comment]
I agree. Emacs packages tend to be backward compatible enough that even development versions don't break compatibility with latest stable versions of emacs. And if they do, it can be fixed by specifying an appropriate version in the quelpa recipe anyway. So I cannot think of any disadvantages of making this the default behaviour.

**Comment by steckerhalter** [comment]
so #97 should address this. it's basically the `package-installed-p` with the check for builtins removed so that it only looks for packages in `package-alist`

**Comment by steckerhalter** [comment]
PR is merged. @bricewge please check if this is what you expected :octocat:

**Comment by bricewge** [comment]
Yes it's fixed now. Thanks a lot!
